import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "@/widgets/navbar/component/navbar";
import { ThemeContextProvider } from "@/application/providers/context/ThemeContext";
import AuthProvider from "@/application/auth/AuthProvider";
import localFont from "next/font/local";
import FixMountProvider from "@/application/providers/fix-mount-provider/FixMountProvider";
import ErrorBoundary from "@/widgets/error-handler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const poppins = localFont({
  src: [
    {
      path: "../../fonts/poppins/Poppins-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../fonts/poppins/Poppins-Medium.ttf",
      weight: "500",
    },
  ],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={[roboto.className, poppins.className].join(" ")}>
        <ErrorBoundary>
          <FixMountProvider>
            <ThemeContextProvider>
              <AuthProvider>
                <header>
                  <Navbar />
                </header>
                {children}
              </AuthProvider>
            </ThemeContextProvider>
          </FixMountProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
