import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/widgets/navbar/component/navbar";
import { ThemeContextProvider } from "@/application/providers/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
